
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{Глобальная карта}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

# Map 30, Global, base 310
{310}{}{Modoc_mine_entrance}
{315}{}{06vault.ogg}
{316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{318}{}{Шахта}

# Map 31, Global, base 320
{320}{}{Modoc_mine_shafts}
{325}{}{06vault.ogg}
{326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{328}{}{Штольни}

# Map 32, Global, base 330
{330}{}{Modoc_getto}
{335}{}{05raider.ogg}
{336}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{338}{}{Гетто}

# Map 33, Global, base 340
{340}{}{Modoc_city_main}
{345}{}{19reno.ogg}
{346}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{348}{}{Модок}

# Map 34, Global, base 350
{350}{}{Modoc_city_floors}
{355}{}{19reno.ogg}
{356}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{358}{}{Этажи}

# Map 35, Global, base 360
{360}{}{Modoc_city_underground}
{365}{}{19reno.ogg}
{366}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{368}{}{Подземка}

# Map 36, Global, base 370
{370}{}{Modoc_farm}
{375}{}{10 - Dystopian Dreams.ogg}
{376}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{378}{}{Ферма}

# Map 37, Global, base 380
{380}{}{Modoc_sawmill}
{385}{}{16follow.ogg}
{386}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{388}{}{Лесопилка}

# Map 38, Global, base 390
{390}{}{Modoc_water_tower}
{395}{}{23world.ogg}
{396}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{398}{}{Вышка}

# Map 39, Global, base 400
{400}{}{Modoc_desert}
{405}{}{57SHK_sinless_From_Seattle.ogg}
{406}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{408}{}{Пустырь}

# Map 40, Global, base 410
{410}{}{Modoc_brown_wood}
{415}{}{21sf.ogg}
{416}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{418}{}{Бурый лес}


#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{Вы наткнулись на @lex who@.}
#{10000011}{}{Вы наткнулись на @lex who@ и @lex player@.}
#{10000012}{}{Вы наткнулись на @lex who@ и банду @lex player@.}
#{10000013}{}{Вы наткнулись на @lex player@.}
#{10000014}{}{Вы наткнулись на банду @lex player@.}
#{10000020}{}{Вы хотите увидеть @lex who@?}
#{10000021}{}{Вы хотите увидеть @lex who@ и @lex player@?}
#{10000022}{}{Вы хотите увидеть @lex who@ и банду @lex player@?}
#{10000023}{}{Вы хотите увидеть @lex player@?}
#{10000024}{}{Вы хотите увидеть банду @lex player@?}
