
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{World Map}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

# Map 30, Global, base 310
{310}{}{Modoc_mine_entrance}
{315}{}{06vault.ogg}
{316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{318}{}{Mine}

# Map 31, Global, base 320
{320}{}{Modoc_mine_shafts}
{325}{}{06vault.ogg}
{326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{328}{}{Mineshafts}

# Map 32, Global, base 330
{330}{}{Modoc_getto}
{335}{}{05raider.ogg}
{336}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{338}{}{Getto}

# Map 33, Global, base 340
{340}{}{Modoc_city_main}
{345}{}{19reno.ogg}
{346}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{348}{}{Modoc}

# Map 34, Global, base 350
{350}{}{Modoc_city_floors}
{355}{}{19reno.ogg}
{356}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{358}{}{Floors}

# Map 35, Global, base 360
{360}{}{Modoc_city_underground}
{365}{}{19reno.ogg}
{366}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{368}{}{Underground}

# Map 36, Global, base 370
{370}{}{Modoc_farm}
{375}{}{10 - Dystopian Dreams.ogg}
{376}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{378}{}{Farm}


#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{You have stumbled upon @lex who@.}
#{10000011}{}{You have stumbled upon @lex who@ and @lex player@.}
#{10000012}{}{You have stumbled upon @lex who@ and the @lex player @ gang.}
#{10000013}{}{You have stumbled upon @lex player@.}
#{10000014}{}{You've stumbled upon the @lex player gang@.}
#{10000020}{}{Do you want to see @lex who@?}
#{10000021}{}{Do you want to see @lex who@ and @lex player@?}
#{10000022}{}{Do you want to see @lex who@ and the @lex player gang@?}
#{10000023}{}{Do you want to see @lex player@?}
#{10000024}{}{Do you want to see the @lex player @ gang?}
